# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 215fc36ecd05367baa9de3f61e76c132f2913537d1173cf9007fc44c93410804d82f62fa65f2eaa3bb70d522dacf957392aa138be942ca5e2bcde2438cf9d96a

test:
  secret_key_base: 7a09c26e19e7a456943230bdb166ab1131c0a75afd7d9b243becec6be76e53e5fbb2db0184fb063a76de05b3d5ab7d391f04c08d176a6ab88b50bb86afac066a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
